spring:
  config:
    import: optional:classpath:application-local-secret.yaml

  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/seed

conn:
  security:
    default-company-code: CONN
